Better Error Messages on not Windows/Linux
impakt73/bass-sys pull request #1
Opened 2021-07-25 16:13 UTC by Chris--B

MacOS builds of bass-sys right now attempt to use the Linux bindings and then fail with obscure errors about file formats. This change adds better checking for that and checks the compile target of the crate, not the build script. This comes up when cross compiling.

See: https://kazlauskas.me/entries/writing-proper-buildrs-scripts.html

2021-08-06 18:11 UTC, Chris--B commented
Bump

2021-08-07 01:29 UTC, impakt73 requested changes

2021-08-07 01:29 UTC, impakt73 commented on build.rs
> +        Ok("windows") => "libbass.so",
These clearly need to be swapped :P

2021-08-07 01:29 UTC, impakt73 commented on build.rs
> +        Ok(unsupported_os) => panic!(
Can you upload the generated bindings for mac please? Ideally I don't want to require the bindgen feature by default.

2021-08-07 02:31 UTC, impakt73 approved these changes

2021-08-07 02:31 UTC, merged